# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#


development:
  adapter: postgresql
  encoding: utf8
  database: simpleapp_production
  pool: 5
  host: localhost
  username: simpleapp
  password: bilal911

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: simpleapp_production
  pool: 5
  host: localhost
  username: simpleapp
  password: bilal911

production:
  adapter: postgresql
  encoding: utf8
  database: simpleapp_production
  pool: 5
  host: localhost
  username: simpleapp
  password: bilal911